import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))


@pytest.fixture(scope="session")
def sample_dir(tmp_path_factory):
    """Fresh sample data generated by scripts/make_sample_data.py (fixed seed)."""
    spec = importlib.util.spec_from_file_location("make_sample_data", ROOT / "scripts" / "make_sample_data.py")
    gen = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gen)
    out = tmp_path_factory.mktemp("sample")
    gen.main(out)
    return out
